#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffb2;
constexpr uint24_t FX_DATA_BYTES = 19805;

constexpr uint24_t characterSheet = 0x000000;
constexpr uint16_t characterSheetWidth  = 12;
constexpr uint16_t characterSheetHeight = 16;
constexpr uint8_t  characterSheetFrames = 12;

constexpr uint24_t creatureSprites = 0x000124;
constexpr uint16_t creatureSpritesWidth  = 32;
constexpr uint16_t creatureSpritesHeight = 32;
constexpr uint8_t  creatureSpritesFrames = 32;

constexpr uint24_t tilesheet = 0x001128;
constexpr uint16_t tilesheetWidth  = 16;
constexpr uint16_t tilesheetHeight = 16;
constexpr uint8_t  tilesheetFrames = 4;

constexpr uint24_t arduboyFont = 0x0011AC;
constexpr uint16_t arduboyFontWidth  = 6;
constexpr uint16_t arduboyFontHeight = 8;
constexpr uint16_t  arduboyFontFrames = 256;

constexpr uint24_t maskedFont = 0x0017B0;
constexpr uint16_t maskedFontWidth  = 16;
constexpr uint16_t maskedFontHeight = 24;
constexpr uint8_t  maskedFontFrames = 128;

constexpr uint24_t encounterRates = 0x0047B4;
constexpr uint24_t op1 = 0x0047FC;
constexpr uint24_t opts = 0x004808;
namespace CreatureData
{
  constexpr uint24_t creature0 = 0x00480C;
  constexpr uint24_t creature1 = 0x00481A;
  constexpr uint24_t creature2 = 0x004827;
  constexpr uint24_t creature3 = 0x004835;
  constexpr uint24_t creature4 = 0x004841;
  constexpr uint24_t creature5 = 0x00484D;
  constexpr uint24_t creature6 = 0x004859;
  constexpr uint24_t creature7 = 0x00485F;
  constexpr uint24_t creature8 = 0x004868;
  constexpr uint24_t creature9 = 0x004875;
  constexpr uint24_t creature10 = 0x00487A;
  constexpr uint24_t creature11 = 0x004880;
  constexpr uint24_t creature12 = 0x004889;
  constexpr uint24_t creature13 = 0x00488F;
  constexpr uint24_t creature14 = 0x004895;
  constexpr uint24_t creature15 = 0x00489A;
  constexpr uint24_t creature16 = 0x0048A5;
  constexpr uint24_t creature17 = 0x0048B0;
  constexpr uint24_t creature18 = 0x0048BA;
  constexpr uint24_t creature19 = 0x0048C2;
  constexpr uint24_t creature20 = 0x0048C9;
  constexpr uint24_t creature21 = 0x0048CE;
  constexpr uint24_t creature22 = 0x0048D3;
  constexpr uint24_t creature23 = 0x0048D9;
  constexpr uint24_t creature24 = 0x0048DD;
  constexpr uint24_t creature25 = 0x0048E1;
  constexpr uint24_t creature26 = 0x0048EA;
  constexpr uint24_t creature27 = 0x0048F1;
  constexpr uint24_t creature28 = 0x0048FC;
  constexpr uint24_t creature29 = 0x004904;
  constexpr uint24_t creature30 = 0x00490C;
  constexpr uint24_t creature31 = 0x004912;
  constexpr uint24_t creatureNames = 0x004917;
  constexpr uint24_t creatureData = 0x004977;
}

namespace MoveData
{
  constexpr uint24_t move0 = 0x004B37;
  constexpr uint24_t move1 = 0x004B3D;
  constexpr uint24_t move2 = 0x004B45;
  constexpr uint24_t move3 = 0x004B4C;
  constexpr uint24_t move4 = 0x004B52;
  constexpr uint24_t move5 = 0x004B59;
  constexpr uint24_t move6 = 0x004B60;
  constexpr uint24_t move7 = 0x004B65;
  constexpr uint24_t move8 = 0x004B6D;
  constexpr uint24_t move9 = 0x004B74;
  constexpr uint24_t move10 = 0x004B7B;
  constexpr uint24_t move11 = 0x004B83;
  constexpr uint24_t move12 = 0x004B88;
  constexpr uint24_t move13 = 0x004B91;
  constexpr uint24_t move14 = 0x004B9A;
  constexpr uint24_t move15 = 0x004BA3;
  constexpr uint24_t move16 = 0x004BAB;
  constexpr uint24_t move17 = 0x004BB0;
  constexpr uint24_t move18 = 0x004BB5;
  constexpr uint24_t move19 = 0x004BBB;
  constexpr uint24_t move20 = 0x004BC1;
  constexpr uint24_t move21 = 0x004BC6;
  constexpr uint24_t move22 = 0x004BCD;
  constexpr uint24_t move23 = 0x004BD2;
  constexpr uint24_t move24 = 0x004BD6;
  constexpr uint24_t move25 = 0x004BDD;
  constexpr uint24_t move26 = 0x004BE8;
  constexpr uint24_t move27 = 0x004BF1;
  constexpr uint24_t move28 = 0x004BF6;
  constexpr uint24_t move29 = 0x004BFB;
  constexpr uint24_t move30 = 0x004C05;
  constexpr uint24_t move31 = 0x004C0A;
  constexpr uint24_t move32 = 0x004C14;
  constexpr uint24_t moveNames = 0x004C16;
  constexpr uint24_t movePack = 0x004C79;
  constexpr uint24_t movelistDebug = 0x004CD9;
  constexpr uint24_t movelist0 = 0x004CDD;
  constexpr uint24_t movelist1 = 0x004CE1;
  constexpr uint24_t movelist2 = 0x004CE5;
  constexpr uint24_t movelist3 = 0x004CE9;
  constexpr uint24_t movelist4 = 0x004CED;
  constexpr uint24_t movelist5 = 0x004CF1;
  constexpr uint24_t movelist6 = 0x004CF5;
  constexpr uint24_t movelist7 = 0x004CF9;
  constexpr uint24_t movelist8 = 0x004CFD;
  constexpr uint24_t movelist9 = 0x004D01;
  constexpr uint24_t movelist10 = 0x004D05;
  constexpr uint24_t movelist11 = 0x004D09;
  constexpr uint24_t movelist12 = 0x004D0D;
  constexpr uint24_t movelist13 = 0x004D11;
  constexpr uint24_t movelist14 = 0x004D15;
  constexpr uint24_t movelist15 = 0x004D19;
  constexpr uint24_t movelist16 = 0x004D1D;
  constexpr uint24_t movelist17 = 0x004D21;
  constexpr uint24_t movelist18 = 0x004D25;
  constexpr uint24_t movelist19 = 0x004D29;
  constexpr uint24_t movelist20 = 0x004D2D;
  constexpr uint24_t movelist21 = 0x004D31;
  constexpr uint24_t movelist22 = 0x004D35;
  constexpr uint24_t movelist23 = 0x004D39;
  constexpr uint24_t movelist24 = 0x004D3D;
  constexpr uint24_t movelist25 = 0x004D41;
  constexpr uint24_t movelist26 = 0x004D45;
  constexpr uint24_t movelist27 = 0x004D49;
  constexpr uint24_t movelist28 = 0x004D4D;
  constexpr uint24_t movelist29 = 0x004D51;
  constexpr uint24_t movelist30 = 0x004D55;
  constexpr uint24_t movelist31 = 0x004D59;
}

