#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf6b4;
constexpr uint24_t FX_DATA_BYTES = 609226;

constexpr uint24_t encounterRates = 0x000000;
constexpr uint24_t op1 = 0x000048;
constexpr uint24_t opts = 0x000054;
namespace CreatureData
{
  constexpr uint24_t creatureData = 0x000058;
}

namespace MoveData
{
  constexpr uint24_t move0 = 0x000218;
  constexpr uint24_t move1 = 0x00021E;
  constexpr uint24_t move2 = 0x000226;
  constexpr uint24_t move3 = 0x00022D;
  constexpr uint24_t move4 = 0x000233;
  constexpr uint24_t move5 = 0x00023A;
  constexpr uint24_t move6 = 0x000241;
  constexpr uint24_t move7 = 0x000246;
  constexpr uint24_t move8 = 0x00024E;
  constexpr uint24_t move9 = 0x000255;
  constexpr uint24_t move10 = 0x00025C;
  constexpr uint24_t move11 = 0x000264;
  constexpr uint24_t move12 = 0x000269;
  constexpr uint24_t move13 = 0x000272;
  constexpr uint24_t move14 = 0x00027B;
  constexpr uint24_t move15 = 0x000284;
  constexpr uint24_t move16 = 0x00028C;
  constexpr uint24_t move17 = 0x000291;
  constexpr uint24_t move18 = 0x000296;
  constexpr uint24_t move19 = 0x00029C;
  constexpr uint24_t move20 = 0x0002A2;
  constexpr uint24_t move21 = 0x0002A7;
  constexpr uint24_t move22 = 0x0002AE;
  constexpr uint24_t move23 = 0x0002B3;
  constexpr uint24_t move24 = 0x0002B7;
  constexpr uint24_t move25 = 0x0002BE;
  constexpr uint24_t move26 = 0x0002C9;
  constexpr uint24_t move27 = 0x0002D2;
  constexpr uint24_t move28 = 0x0002D7;
  constexpr uint24_t move29 = 0x0002DC;
  constexpr uint24_t move30 = 0x0002E6;
  constexpr uint24_t move31 = 0x0002EB;
  constexpr uint24_t move32 = 0x0002F5;
  constexpr uint24_t moveNames = 0x0002F7;
}

namespace EventData
{
  constexpr uint24_t m1e1Text = 0x00035A;
  constexpr uint24_t m1e1 = 0x000367;
  constexpr uint24_t m1eTable = 0x00036A;
  constexpr uint24_t m1s1e1Text = 0x000376;
  constexpr uint24_t m1s1e1 = 0x000385;
  constexpr uint24_t m1s1e21Text = 0x000388;
  constexpr uint24_t m1s1e2 = 0x000397;
  constexpr uint24_t m1s1eTable = 0x00039A;
  constexpr uint24_t m1Table = 0x0003A6;
  constexpr uint24_t eventTable = 0x0003AC;
}

namespace MapData
{
  constexpr uint24_t map1 = 0x0003AF;
  constexpr uint24_t house1 = 0x000607;
  constexpr uint24_t m1submaps = 0x000647;
  constexpr uint24_t m1submapcount = 0x00064A;
  constexpr uint24_t m1widths = 0x00064B;
  constexpr uint24_t m1heights = 0x00064D;
  constexpr uint24_t map1Warps = 0x00064F;
  constexpr uint24_t house1Warps = 0x000657;
  constexpr uint24_t m1warpCounts = 0x00065B;
  constexpr uint24_t m1warps = 0x00065D;
  constexpr uint24_t warps = 0x000663;
  constexpr uint24_t maps = 0x000666;
}

namespace MoveLists
{
  constexpr uint24_t moveList = 0x000678;
}

namespace MenuFXData
{
  constexpr uint24_t attackText = 0x0006F8;
  constexpr uint24_t enemyAttackText = 0x000709;
  constexpr uint24_t damageText = 0x000716;
  constexpr uint24_t hpText = 0x000723;
  constexpr uint24_t atkText = 0x000728;
  constexpr uint24_t defText = 0x00072E;
  constexpr uint24_t spdText = 0x000734;
  constexpr uint24_t satkText = 0x00073A;
  constexpr uint24_t sdefText = 0x000741;
  constexpr uint24_t pointerText = 0x000748;
  constexpr uint24_t SPIRIT = 0x00074A;
  constexpr uint24_t WATER = 0x000751;
  constexpr uint24_t WIND = 0x000757;
  constexpr uint24_t EARTH = 0x00075C;
  constexpr uint24_t FIRE = 0x000762;
  constexpr uint24_t LIGHTNING = 0x000767;
  constexpr uint24_t PLANT = 0x000771;
  constexpr uint24_t ELDER = 0x000777;
  constexpr uint24_t NONE = 0x00077D;
  constexpr uint24_t Fainted = 0x00077E;
  constexpr uint24_t SwitchIn = 0x000786;
  constexpr uint24_t win = 0x000797;
  constexpr uint24_t lose = 0x00079F;
  constexpr uint24_t escaped = 0x0007AA;
  constexpr uint24_t changedIn = 0x0007B6;
  constexpr uint24_t quarter = 0x0007CA;
  constexpr uint24_t half = 0x0007DC;
  constexpr uint24_t doubled = 0x0007E9;
  constexpr uint24_t quad = 0x0007F7;
  constexpr uint24_t damage = 0x000809;
  constexpr uint24_t physical = 0x000810;
  constexpr uint24_t special = 0x000815;
  constexpr uint24_t power = 0x00081A;
  constexpr uint24_t move = 0x000821;
  constexpr uint24_t change = 0x000826;
  constexpr uint24_t escape = 0x00082D;
  constexpr uint24_t gather = 0x000834;
}

namespace Teams
{
namespace StockCreatures
{
    constexpr uint24_t null = 0x00083B;
    constexpr uint24_t SquibbleSnail = 0x000840;
    constexpr uint24_t SquableSnail = 0x000845;
    constexpr uint24_t ScrambleSnail = 0x00084A;
    constexpr uint24_t SkitterCrab = 0x00084F;
    constexpr uint24_t ScatterCrab = 0x000854;
    constexpr uint24_t ShatterCrab = 0x000859;
    constexpr uint24_t squid = 0x00085E;
    constexpr uint24_t bigsquid = 0x000863;
    constexpr uint24_t BiggestSquid = 0x000868;
    constexpr uint24_t bell = 0x00086D;
    constexpr uint24_t ember = 0x000872;
    constexpr uint24_t cuircuit = 0x000877;
    constexpr uint24_t hedge = 0x00087C;
    constexpr uint24_t cloud = 0x000881;
    constexpr uint24_t rock = 0x000886;
    constexpr uint24_t wiggleworm = 0x00088B;
    constexpr uint24_t waggleworm = 0x000890;
    constexpr uint24_t skimskate = 0x000895;
    constexpr uint24_t skimray = 0x00089A;
    constexpr uint24_t billow = 0x00089F;
    constexpr uint24_t howl = 0x0008A4;
    constexpr uint24_t item = 0x0008A9;
    constexpr uint24_t item2 = 0x0008AE;
    constexpr uint24_t zip = 0x0008B3;
    constexpr uint24_t zap = 0x0008B8;
    constexpr uint24_t suculent = 0x0008BD;
    constexpr uint24_t cactus = 0x0008C2;
    constexpr uint24_t flickerfly = 0x0008C7;
    constexpr uint24_t flitfly = 0x0008CC;
    constexpr uint24_t dragon = 0x0008D1;
    constexpr uint24_t skull = 0x0008D6;
    constexpr uint24_t ardu = 0x0008DB;
}

namespace Names
{
    constexpr uint24_t jimbo = 0x0008E0;
}

  constexpr uint24_t teamList = 0x0008E6;
}

constexpr uint24_t testmap = 0x000A75;
constexpr uint24_t numbersblack = 0x000CB5;
constexpr uint24_t creatureSprites = 0x001D1D;
constexpr uint24_t fieldBacground = 0x007D1D;
constexpr uint24_t NewecreatureSprites = 0x00891D;
constexpr uint24_t numberswhite = 0x01491D;
constexpr uint24_t singlenumberswhite = 0x015985;
constexpr uint24_t fightMenu = 0x015A39;
constexpr uint24_t singlenumbersblack = 0x016C39;
constexpr uint24_t ArduFont = 0x016CED;
constexpr uint24_t moveInfo = 0x017422;
constexpr uint24_t worldTiles = 0x0176F2;
constexpr uint24_t characterSheet = 0x017CF2;
constexpr uint24_t tiles = 0x018052;
constexpr uint24_t maskedFont = 0x02A052;
constexpr uint24_t npc = 0x033052;
constexpr uint24_t ecreatureSprites = 0x033112;
constexpr uint24_t arduboyFont = 0x039112;
constexpr uint24_t battleMenu = 0x03A312;
constexpr uint24_t blankMenu = 0x03A792;
constexpr uint24_t ArduFontTrimmed = 0x03B092;
constexpr uint24_t tilesheet = 0x03B4F7;
constexpr uint24_t letters = 0x03C0F7;
constexpr uint24_t amove20 = 0x0480F7;
constexpr uint24_t amove3 = 0x04818D;
constexpr uint24_t creature24 = 0x048241;
constexpr uint24_t special = 0x0482B9;
constexpr uint24_t creature30 = 0x04836D;
constexpr uint24_t damage = 0x048421;
constexpr uint24_t amove29 = 0x048511;
constexpr uint24_t amove4 = 0x04863D;
constexpr uint24_t amove5 = 0x04870F;
constexpr uint24_t status = 0x0487E1;
constexpr uint24_t creature6 = 0x0488B3;
constexpr uint24_t amove7 = 0x048967;
constexpr uint24_t amove25 = 0x048A57;
constexpr uint24_t creature27 = 0x048BA1;
constexpr uint24_t wind = 0x048CEB;
constexpr uint24_t lightning = 0x048D9F;
constexpr uint24_t creature0 = 0x048EE9;
constexpr uint24_t creature9 = 0x04908D;
constexpr uint24_t amove12 = 0x049123;
constexpr uint24_t amove13 = 0x049231;
constexpr uint24_t sdefText = 0x04933F;
constexpr uint24_t amove6 = 0x049411;
constexpr uint24_t amove15 = 0x0494A7;
constexpr uint24_t satkText = 0x049597;
constexpr uint24_t creature29 = 0x049669;
constexpr uint24_t creature28 = 0x049759;
constexpr uint24_t creature11 = 0x049849;
constexpr uint24_t creature12 = 0x049957;
constexpr uint24_t creature13 = 0x049A0B;
constexpr uint24_t creature25 = 0x049ABF;
constexpr uint24_t creature3 = 0x049BCD;
constexpr uint24_t amove26 = 0x049D35;
constexpr uint24_t spdText = 0x049E43;
constexpr uint24_t creature26 = 0x049EF7;
constexpr uint24_t amove14 = 0x049FC9;
constexpr uint24_t gather = 0x04A0D7;
constexpr uint24_t amove30 = 0x04A1A9;
constexpr uint24_t amove24 = 0x04A23F;
constexpr uint24_t fire = 0x04A311;
constexpr uint24_t creature19 = 0x04A3C5;
constexpr uint24_t lose = 0x04A497;
constexpr uint24_t creature8 = 0x04A5FF;
constexpr uint24_t creature5 = 0x04A785;
constexpr uint24_t creature4 = 0x04A8ED;
constexpr uint24_t Fainted = 0x04AA55;
constexpr uint24_t amove27 = 0x04AB63;
constexpr uint24_t creature15 = 0x04ABF9;
constexpr uint24_t half = 0x04AD43;
constexpr uint24_t creature23 = 0x04AEE7;
constexpr uint24_t hpText = 0x04AF5F;
constexpr uint24_t amove2 = 0x04AFF5;
constexpr uint24_t elder = 0x04B0C7;
constexpr uint24_t plant = 0x04B199;
constexpr uint24_t amove1 = 0x04B26B;
constexpr uint24_t water = 0x04B35B;
constexpr uint24_t enemyAttackText = 0x04B42D;
constexpr uint24_t atkText = 0x04B5D1;
constexpr uint24_t amove9 = 0x04B685;
constexpr uint24_t amove8 = 0x04B757;
constexpr uint24_t defText = 0x04B829;
constexpr uint24_t none = 0x04B8DD;
constexpr uint24_t earth = 0x04B991;
constexpr uint24_t creature10 = 0x04BA63;
constexpr uint24_t amove32 = 0x04BB17;
constexpr uint24_t damageText = 0x04BB35;
constexpr uint24_t physical = 0x04BCD9;
constexpr uint24_t win = 0x04BD8D;
constexpr uint24_t amove21 = 0x04BE9B;
constexpr uint24_t amove19 = 0x04BF6D;
constexpr uint24_t amove18 = 0x04C021;
constexpr uint24_t creature14 = 0x04C0D5;
constexpr uint24_t amove28 = 0x04C16B;
constexpr uint24_t changedIn = 0x04C201;
constexpr uint24_t amove16 = 0x04C477;
constexpr uint24_t creature2 = 0x04C50D;
constexpr uint24_t amove17 = 0x04C6B1;
constexpr uint24_t amove22 = 0x04C747;
constexpr uint24_t amove0 = 0x04C7DD;
constexpr uint24_t escaped = 0x04C891;
constexpr uint24_t creature17 = 0x04CA17;
constexpr uint24_t creature20 = 0x04CB43;
constexpr uint24_t creature21 = 0x04CBD9;
constexpr uint24_t quad = 0x04CC6F;
constexpr uint24_t creature7 = 0x04CEA9;
constexpr uint24_t SwitchIn = 0x04CFB7;
constexpr uint24_t amove11 = 0x04D1D3;
constexpr uint24_t creature16 = 0x04D269;
constexpr uint24_t power = 0x04D3B3;
constexpr uint24_t spirit = 0x04D4A3;
constexpr uint24_t doubled = 0x04D593;
constexpr uint24_t amove23 = 0x04D755;
constexpr uint24_t pointerText = 0x04D7CD;
constexpr uint24_t attackText = 0x04D827;
constexpr uint24_t move = 0x04DA43;
constexpr uint24_t creature18 = 0x04DAF7;
constexpr uint24_t amove31 = 0x04DBE7;
constexpr uint24_t escape = 0x04DD13;
constexpr uint24_t creature1 = 0x04DE03;
constexpr uint24_t applied = 0x04DF89;
constexpr uint24_t amove10 = 0x04E14B;
constexpr uint24_t quarter = 0x04E23B;
constexpr uint24_t creature22 = 0x04E475;
constexpr uint24_t change = 0x04E529;
constexpr uint24_t creature31 = 0x04E619;
namespace CreatureNames
{
  constexpr uint24_t CreatureNames = 0x04E6AF;
}

namespace MoveNames
{
  constexpr uint24_t MoveNames = 0x04E70F;
}

namespace MenuStrings
{
  constexpr uint24_t MenuStrings = 0x04E772;
}

namespace EffectStrings
{
  constexpr uint24_t EffectStrings = 0x04E7E4;
}

constexpr uint24_t basicBeamR = 0x04E7E7;
constexpr uint24_t basicBeamL = 0x04FFE7;
constexpr uint24_t BasicWaveR = 0x0517E7;
constexpr uint24_t BasicWaveL = 0x052FE7;
constexpr uint24_t fontTrimmed = 0x0547E7;
constexpr uint16_t fontTrimmedWidth  = 5;
constexpr uint16_t fontTrimmedHeight = 6;
constexpr uint8_t  fontTrimmedFrames = 75;

constexpr uint24_t opponent_seeds = 0x054962;
constexpr uint24_t type_table = 0x054AB8;
constexpr uint24_t move_table = 0x054AF8;
constexpr uint24_t map_data = 0x054BA8;
constexpr uint24_t raw_map_data = 0x074BA8;
constexpr uint24_t raw_map_text = 0x094BA8;
