#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfca4;
constexpr uint24_t FX_DATA_BYTES = 219980;

constexpr uint24_t encounterRates = 0x000000;
constexpr uint24_t op1 = 0x000048;
constexpr uint24_t opts = 0x000054;
namespace CreatureData
{
  constexpr uint24_t creatureData = 0x000058;
}

namespace MoveData
{
  constexpr uint24_t move0 = 0x000218;
  constexpr uint24_t move1 = 0x00021E;
  constexpr uint24_t move2 = 0x000226;
  constexpr uint24_t move3 = 0x00022D;
  constexpr uint24_t move4 = 0x000233;
  constexpr uint24_t move5 = 0x00023A;
  constexpr uint24_t move6 = 0x000241;
  constexpr uint24_t move7 = 0x000246;
  constexpr uint24_t move8 = 0x00024E;
  constexpr uint24_t move9 = 0x000255;
  constexpr uint24_t move10 = 0x00025C;
  constexpr uint24_t move11 = 0x000264;
  constexpr uint24_t move12 = 0x000269;
  constexpr uint24_t move13 = 0x000272;
  constexpr uint24_t move14 = 0x00027B;
  constexpr uint24_t move15 = 0x000284;
  constexpr uint24_t move16 = 0x00028C;
  constexpr uint24_t move17 = 0x000291;
  constexpr uint24_t move18 = 0x000296;
  constexpr uint24_t move19 = 0x00029C;
  constexpr uint24_t move20 = 0x0002A2;
  constexpr uint24_t move21 = 0x0002A7;
  constexpr uint24_t move22 = 0x0002AE;
  constexpr uint24_t move23 = 0x0002B3;
  constexpr uint24_t move24 = 0x0002B7;
  constexpr uint24_t move25 = 0x0002BE;
  constexpr uint24_t move26 = 0x0002C9;
  constexpr uint24_t move27 = 0x0002D2;
  constexpr uint24_t move28 = 0x0002D7;
  constexpr uint24_t move29 = 0x0002DC;
  constexpr uint24_t move30 = 0x0002E6;
  constexpr uint24_t move31 = 0x0002EB;
  constexpr uint24_t move32 = 0x0002F5;
  constexpr uint24_t moveNames = 0x0002F7;
}

namespace EventData
{
  constexpr uint24_t m1e1Text = 0x00035A;
  constexpr uint24_t m1e1 = 0x000367;
  constexpr uint24_t m1eTable = 0x00036A;
  constexpr uint24_t m1s1e1Text = 0x000376;
  constexpr uint24_t m1s1e1 = 0x000385;
  constexpr uint24_t m1s1e21Text = 0x000388;
  constexpr uint24_t m1s1e2 = 0x000397;
  constexpr uint24_t m1s1eTable = 0x00039A;
  constexpr uint24_t m1Table = 0x0003A6;
  constexpr uint24_t eventTable = 0x0003AC;
}

namespace MapData
{
  constexpr uint24_t map1 = 0x0003AF;
  constexpr uint24_t house1 = 0x000607;
  constexpr uint24_t m1submaps = 0x000647;
  constexpr uint24_t m1submapcount = 0x00064A;
  constexpr uint24_t m1widths = 0x00064B;
  constexpr uint24_t m1heights = 0x00064D;
  constexpr uint24_t map1Warps = 0x00064F;
  constexpr uint24_t house1Warps = 0x000657;
  constexpr uint24_t m1warpCounts = 0x00065B;
  constexpr uint24_t m1warps = 0x00065D;
  constexpr uint24_t warps = 0x000663;
  constexpr uint24_t maps = 0x000666;
}

namespace MoveLists
{
  constexpr uint24_t moveList = 0x000678;
}

namespace MenuFXData
{
  constexpr uint24_t attackText = 0x0006F8;
  constexpr uint24_t enemyAttackText = 0x000709;
  constexpr uint24_t damageText = 0x000716;
  constexpr uint24_t hpText = 0x000723;
  constexpr uint24_t atkText = 0x000728;
  constexpr uint24_t defText = 0x00072E;
  constexpr uint24_t spdText = 0x000734;
  constexpr uint24_t satkText = 0x00073A;
  constexpr uint24_t sdefText = 0x000741;
  constexpr uint24_t pointerText = 0x000748;
  constexpr uint24_t SPIRIT = 0x00074A;
  constexpr uint24_t WATER = 0x000751;
  constexpr uint24_t WIND = 0x000757;
  constexpr uint24_t EARTH = 0x00075C;
  constexpr uint24_t FIRE = 0x000762;
  constexpr uint24_t LIGHTNING = 0x000767;
  constexpr uint24_t PLANT = 0x000771;
  constexpr uint24_t ELDER = 0x000777;
  constexpr uint24_t NONE = 0x00077D;
  constexpr uint24_t Fainted = 0x00077E;
  constexpr uint24_t SwitchIn = 0x000786;
  constexpr uint24_t win = 0x000797;
  constexpr uint24_t lose = 0x00079F;
  constexpr uint24_t escaped = 0x0007AA;
  constexpr uint24_t changedIn = 0x0007B6;
  constexpr uint24_t quarter = 0x0007CA;
  constexpr uint24_t half = 0x0007DC;
  constexpr uint24_t doubled = 0x0007E9;
  constexpr uint24_t quad = 0x0007F7;
  constexpr uint24_t damage = 0x000809;
  constexpr uint24_t physical = 0x000810;
  constexpr uint24_t special = 0x000815;
  constexpr uint24_t power = 0x00081A;
  constexpr uint24_t move = 0x000821;
  constexpr uint24_t change = 0x000826;
  constexpr uint24_t escape = 0x00082D;
  constexpr uint24_t gather = 0x000834;
}

namespace Teams
{
namespace StockCreatures
{
    constexpr uint24_t null = 0x00083B;
    constexpr uint24_t SquibbleSnail = 0x000840;
    constexpr uint24_t SquableSnail = 0x000845;
    constexpr uint24_t ScrambleSnail = 0x00084A;
    constexpr uint24_t SkitterCrab = 0x00084F;
    constexpr uint24_t ScatterCrab = 0x000854;
    constexpr uint24_t ShatterCrab = 0x000859;
    constexpr uint24_t squid = 0x00085E;
    constexpr uint24_t bigsquid = 0x000863;
    constexpr uint24_t BiggestSquid = 0x000868;
    constexpr uint24_t bell = 0x00086D;
    constexpr uint24_t ember = 0x000872;
    constexpr uint24_t cuircuit = 0x000877;
    constexpr uint24_t hedge = 0x00087C;
    constexpr uint24_t cloud = 0x000881;
    constexpr uint24_t rock = 0x000886;
    constexpr uint24_t wiggleworm = 0x00088B;
    constexpr uint24_t waggleworm = 0x000890;
    constexpr uint24_t skimskate = 0x000895;
    constexpr uint24_t skimray = 0x00089A;
    constexpr uint24_t billow = 0x00089F;
    constexpr uint24_t howl = 0x0008A4;
    constexpr uint24_t item = 0x0008A9;
    constexpr uint24_t item2 = 0x0008AE;
    constexpr uint24_t zip = 0x0008B3;
    constexpr uint24_t zap = 0x0008B8;
    constexpr uint24_t suculent = 0x0008BD;
    constexpr uint24_t cactus = 0x0008C2;
    constexpr uint24_t flickerfly = 0x0008C7;
    constexpr uint24_t flitfly = 0x0008CC;
    constexpr uint24_t dragon = 0x0008D1;
    constexpr uint24_t skull = 0x0008D6;
    constexpr uint24_t ardu = 0x0008DB;
}

namespace Names
{
    constexpr uint24_t jimbo = 0x0008E0;
}

  constexpr uint24_t teamList = 0x0008E6;
}

constexpr uint24_t testmap = 0x000A75;
constexpr uint24_t fieldBacground = 0x000CB5;
constexpr uint24_t arduboyFont = 0x0018B7;
constexpr uint24_t letters = 0x002AB9;
constexpr uint24_t tilesheet = 0x00EABB;
constexpr uint24_t moveInfo = 0x00F6BD;
constexpr uint24_t singlenumberswhite = 0x00F98F;
constexpr uint24_t fightMenu = 0x00FA45;
constexpr uint24_t ecreatureSprites = 0x010C47;
constexpr uint24_t maskedFont = 0x016C49;
constexpr uint24_t numberswhite = 0x01FC4B;
constexpr uint24_t numbersblack = 0x020CB5;
constexpr uint24_t battleMenu = 0x021D1F;
constexpr uint24_t Font = 0x0221A1;
constexpr uint24_t creatureSprites = 0x0228D8;
constexpr uint24_t characterSheet = 0x0288DA;
constexpr uint24_t singlenumbersblack = 0x028C3C;
constexpr uint24_t worldTiles = 0x028CF2;
constexpr uint24_t npc = 0x0292F4;
constexpr uint24_t amove5 = 0x0293B6;
constexpr uint24_t pointerText = 0x02948A;
constexpr uint24_t creature28 = 0x0294E6;
constexpr uint24_t creature27 = 0x0295D8;
constexpr uint24_t amove23 = 0x029724;
constexpr uint24_t amove22 = 0x02979E;
constexpr uint24_t atkText = 0x029836;
constexpr uint24_t spirit = 0x0298EC;
constexpr uint24_t creature29 = 0x0299DE;
constexpr uint24_t creature0 = 0x029AD0;
constexpr uint24_t wind = 0x029C76;
constexpr uint24_t creature14 = 0x029D2C;
constexpr uint24_t creature1 = 0x029DC4;
constexpr uint24_t amove2 = 0x029F4C;
constexpr uint24_t enemyAttackText = 0x02A020;
constexpr uint24_t creature3 = 0x02A1C6;
constexpr uint24_t power = 0x02A330;
constexpr uint24_t win = 0x02A422;
constexpr uint24_t creature9 = 0x02A532;
constexpr uint24_t fire = 0x02A5CA;
constexpr uint24_t quarter = 0x02A680;
constexpr uint24_t move = 0x02A8BC;
constexpr uint24_t hpText = 0x02A972;
constexpr uint24_t water = 0x02AA0A;
constexpr uint24_t creature7 = 0x02AADE;
constexpr uint24_t creature30 = 0x02ABEE;
constexpr uint24_t creature17 = 0x02ACA4;
constexpr uint24_t spdText = 0x02ADD2;
constexpr uint24_t creature4 = 0x02AE88;
constexpr uint24_t amove24 = 0x02AFF2;
constexpr uint24_t special = 0x02B0C6;
constexpr uint24_t creature15 = 0x02B17C;
constexpr uint24_t quad = 0x02B2C8;
constexpr uint24_t attackText = 0x02B504;
constexpr uint24_t amove27 = 0x02B722;
constexpr uint24_t amove30 = 0x02B7BA;
constexpr uint24_t creature26 = 0x02B852;
constexpr uint24_t creature6 = 0x02B926;
constexpr uint24_t creature12 = 0x02B9DC;
constexpr uint24_t damage = 0x02BA92;
constexpr uint24_t Fainted = 0x02BB84;
constexpr uint24_t amove28 = 0x02BC94;
constexpr uint24_t amove21 = 0x02BD2C;
constexpr uint24_t amove13 = 0x02BE00;
constexpr uint24_t satkText = 0x02BF10;
constexpr uint24_t earth = 0x02BFE4;
constexpr uint24_t creature23 = 0x02C0B8;
constexpr uint24_t amove3 = 0x02C132;
constexpr uint24_t amove11 = 0x02C1E8;
constexpr uint24_t doubled = 0x02C280;
constexpr uint24_t amove0 = 0x02C444;
constexpr uint24_t amove31 = 0x02C4FA;
constexpr uint24_t creature20 = 0x02C628;
constexpr uint24_t creature21 = 0x02C6C0;
constexpr uint24_t creature19 = 0x02C758;
constexpr uint24_t none = 0x02C82C;
constexpr uint24_t applied = 0x02C8E2;
constexpr uint24_t amove4 = 0x02CAA6;
constexpr uint24_t amove15 = 0x02CB7A;
constexpr uint24_t amove25 = 0x02CC6C;
constexpr uint24_t damageText = 0x02CDB8;
constexpr uint24_t creature2 = 0x02CF5E;
constexpr uint24_t creature18 = 0x02D104;
constexpr uint24_t half = 0x02D1F6;
constexpr uint24_t changedIn = 0x02D39C;
constexpr uint24_t SwitchIn = 0x02D614;
constexpr uint24_t elder = 0x02D832;
constexpr uint24_t amove9 = 0x02D906;
constexpr uint24_t escape = 0x02D9DA;
constexpr uint24_t amove20 = 0x02DACC;
constexpr uint24_t plant = 0x02DB64;
constexpr uint24_t amove8 = 0x02DC38;
constexpr uint24_t sdefText = 0x02DD0C;
constexpr uint24_t amove29 = 0x02DDE0;
constexpr uint24_t lightning = 0x02DF0E;
constexpr uint24_t creature22 = 0x02E05A;
constexpr uint24_t amove32 = 0x02E110;
constexpr uint24_t amove7 = 0x02E130;
constexpr uint24_t creature31 = 0x02E222;
constexpr uint24_t escaped = 0x02E2BA;
constexpr uint24_t defText = 0x02E442;
constexpr uint24_t amove16 = 0x02E4F8;
constexpr uint24_t creature5 = 0x02E590;
constexpr uint24_t creature8 = 0x02E6FA;
constexpr uint24_t amove26 = 0x02E882;
constexpr uint24_t amove19 = 0x02E992;
constexpr uint24_t physical = 0x02EA48;
constexpr uint24_t amove6 = 0x02EAFE;
constexpr uint24_t creature13 = 0x02EB96;
constexpr uint24_t amove12 = 0x02EC4C;
constexpr uint24_t amove18 = 0x02ED5C;
constexpr uint24_t amove17 = 0x02EE12;
constexpr uint24_t gather = 0x02EEAA;
constexpr uint24_t creature11 = 0x02EF7E;
constexpr uint24_t lose = 0x02F08E;
constexpr uint24_t amove10 = 0x02F1F8;
constexpr uint24_t creature24 = 0x02F2EA;
constexpr uint24_t amove1 = 0x02F364;
constexpr uint24_t creature16 = 0x02F456;
constexpr uint24_t change = 0x02F5A2;
constexpr uint24_t creature10 = 0x02F694;
constexpr uint24_t creature25 = 0x02F74A;
constexpr uint24_t amove14 = 0x02F85A;
namespace CreatureNames
{
  constexpr uint24_t CreatureNames = 0x02F96A;
}

namespace MoveNames
{
  constexpr uint24_t MoveNames = 0x02F9CA;
}

namespace MenuStrings
{
  constexpr uint24_t MenuStrings = 0x02FA2D;
}

namespace EffectStrings
{
  constexpr uint24_t EffectStrings = 0x02FA9C;
}

constexpr uint24_t BasicWaveR = 0x02FA9F;
constexpr uint24_t basicBeamR = 0x0312A1;
constexpr uint24_t basicBeamL = 0x032AA3;
constexpr uint24_t BasicWaveL = 0x0342A5;
namespace MoveData
{
  constexpr uint24_t movePack = 0x035AA7;
}

